import 'dart:async';
import 'dart:io';
import 'package:geolocator/geolocator.dart';
import 'package:image_picker/image_picker.dart';
import '../models/product_model.dart';
import '../models/comment_model.dart';
import 'api_service.dart';

class ProductService {
  final ApiService _apiService = ApiService();

  // Create product
  Future<String> createProduct(ProductModel product, List<XFile> images) async {
    try {
      // Upload images
      List<String> imageUrls = await _uploadImages(images);

      // Create product with image URLs
      // Note: product.id will be generated by the server, so we don't send it or we ignore it
      final productData = product.toMap();
      productData['imageUrls'] = imageUrls;
      
      // We need to ensure the server handles the ID generation or we send a temporary one
      // The PHP script generates a new ID.
      
      final response = await _apiService.post('products/create.php', productData);
      return response['id'];
    } catch (e) {
      print('Create product error: $e');
      rethrow;
    }
  }

  // Update product
  Future<void> updateProduct(
      ProductModel product, List<XFile>? newImages) async {
    try {
      // TODO: Implement update API
    } catch (e) {
      print('Update product error: $e');
      rethrow;
    }
  }

  // Delete product
  Future<void> deleteProduct(String productId) async {
    try {
      // TODO: Implement delete API
    } catch (e) {
      print('Delete product error: $e');
      rethrow;
    }
  }

  // Get product by ID
  Future<ProductModel?> getProduct(String productId) async {
    // TODO: Implement get by ID API
    return null;
  }

  // Get all approved products
  // Changed from Stream to Future
  Future<List<ProductModel>> getApprovedProducts() async {
    try {
      final response = await _apiService.get('products/read.php');
      if (response is List) {
        return response.map((data) => ProductModel.fromMap(data)).toList();
      }
      return [];
    } catch (e) {
      print('Get approved products error: $e');
      return [];
    }
  }

  // Get products by user
  Future<List<ProductModel>> getUserProducts(String userId) async {
    // TODO: Implement get user products API (filter on server or client)
    // For now, fetch all and filter
    final all = await getApprovedProducts();
    return all.where((p) => p.ownerId == userId).toList();
  }

  // Get pending products (for admin)
  Future<List<ProductModel>> getPendingProducts() async {
    // TODO: Implement get pending API
    return [];
  }

  // Approve product (admin)
  Future<void> approveProduct(String productId) async {
    // TODO: Implement approve API
  }

  // Reject product (admin)
  Future<void> rejectProduct(String productId) async {
    // TODO: Implement reject API
  }

  // Mark product as sold out
  Future<void> markAsSoldOut(String productId) async {
    // TODO: Implement mark sold out API
  }

  // Increment view count
  Future<void> incrementViewCount(String productId) async {
    // TODO: Implement increment view API
  }

  // Search products with filters
  Future<List<ProductModel>> searchProducts({
    String? keyword,
    ProductCategory? category,
    ProductCondition? condition,
    Position? userPosition,
    double? maxDistance, // in km
  }) async {
    // TODO: Implement search API
    return [];
  }

  // Add comment
  Future<void> addComment(CommentModel comment) async {
    // TODO: Implement add comment API
  }

  // Get comments for product
  Future<List<CommentModel>> getProductComments(String productId) async {
    // TODO: Implement get comments API
    return [];
  }

  // Delete comment
  Future<void> deleteComment(String commentId) async {
    // TODO: Implement delete comment API
  }

  // Helper: Upload images
  Future<List<String>> _uploadImages(List<XFile> images) async {
    try {
      List<String> urls = [];
      for (var image in images) {
        String url = await _apiService.uploadImage(File(image.path));
        urls.add(url);
      }
      return urls;
    } catch (e) {
      print('Error uploading images: $e');
      rethrow;
    }
  }
}
