// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYOUoDBTFc4PuOIeOU-w3wIPo2mj_Voys',
    appId: '1:914000987936:web:b93782cee0e8fc700cb945',
    messagingSenderId: '914000987936',
    projectId: 'appdocu1-993dc',
    authDomain: 'appdocu1-993dc.firebaseapp.com',
    storageBucket: 'appdocu1-993dc.firebasestorage.app',
    measurementId: 'G-Q7JNGF4RYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYOUoDBTFc4PuOIeOU-w3wIPo2mj_Voys',
    appId: '1:914000987936:android:b93782cee0e8fc700cb945',
    messagingSenderId: '914000987936',
    projectId: 'appdocu1-993dc',
    storageBucket: 'appdocu1-993dc.firebasestorage.app',
  );
}
